### ISSUE TITLE
カンマ後には半角スペースを入れる

### ISSUE THREAD

**Issue by norotime** [Grape-from-kai/battle-maker#3]
https://github.com/Grape-from-kai/battle-maker/blob/add8f1b5ee30c8f7aee67ed18294b665f1e77a80/app/controllers/battles_controller.rb#L2

**Comment by norotime** [comment]
@Grape-from-kai 対応したコミットを紐づけてくださいねーー！

**Comment by OkadaSatoshi** [comment]
@norotime github上でこのイシュ―をクローズする前にコマンドライン上で"git commit -m 'Close#3'"をやり、プッシュしてもイシュ―が閉じられなかったのですが、やり方が間違っているのでしょうか・・・？

**Comment by OkadaSatoshi** [comment]
@norotime やり直してみたらできました。お騒がせしました。
