### ISSUE TITLE
データのソート等加工はモデルで済ませる

### ISSUE THREAD

**Issue by norotime** [Grape-from-kai/battle-maker#4]
https://github.com/Grape-from-kai/battle-maker/blob/add8f1b5ee30c8f7aee67ed18294b665f1e77a80/app/controllers/battles_controller.rb#L5

**Comment by OkadaSatoshi** [comment]
https://github.com/Grape-from-kai/battle-maker/blob/49a425bb04a675b5984ddac00e2beb8073ca7a1d/app/controllers/users_controller.rb#L6
battles_controllerはなおした ここも直す

**Comment by norotime** [comment]
@Grape-from-kai どんどん直しましょう！
銀行の
窓口担当者＝コントローラ
バックオフィスの各専任担当者＝モデル
と思って下さい。

誰が何をするともっとも効率的かを考えましょう。
何でもかんでも窓口の方にやらせると、窓口の人のやっていることがぐちゃぐちゃになります。
