### ISSUE TITLE
アソシエーションメソッドを使い一行で実装する

### ISSUE THREAD

**Issue by norotime** [Grape-from-kai/battle-maker#5]
https://github.com/Grape-from-kai/battle-maker/blob/add8f1b5ee30c8f7aee67ed18294b665f1e77a80/app/controllers/battles_controller.rb#L18

https://railsguides.jp/association_basics.html#has-many%E3%81%A7%E8%BF%BD%E5%8A%A0%E3%81%95%E3%82%8C%E3%82%8B%E3%83%A1%E3%82%BD%E3%83%83%E3%83%89-collection-build-attributes

**Comment by OkadaSatoshi** [comment]
@norotime お世話になっております。当イシュ―解決のため。アソシエーションメソッドで表現しようとしたのですが、`@battle = current_user.battles.new(battle_params)`にしてもuser_idが登録されません。
https://1drv.ms/u/s!AqqJCKAa6lWEsAgsFsFWwPKO09ev
このようなエラー表示になります。

https://ide.c9.io/sadakao/battle-maker
こちらはcloud9のリンクになります。
この状況に関して、ご意見を伺いたいです。お忙しいとは存じますが、よろしくお願いいたします。

**Comment by norotime** [comment]
@battle = current_user.battles. *build* (battle_params)
ではダメですか？

**Comment by OkadaSatoshi** [comment]
今試してみましたが、だめでした。同じエラーが吐かれます

**Comment by norotime** [comment]
@Grape-from-kai エラーが見えないですよー。gitHubにアップロードしてくだせえ。

**Comment by OkadaSatoshi** [comment]
遅くなりました。ご確認お願いします。
https://github.com/Grape-from-kai/battle-maker/wiki

**Comment by norotime** [comment]
@Grape-from-kai 画面コピーをここにドラッグアンドドロップして欲しかったです。
user_idがnlになるということですか？それともバリデーションに引っかかるということですか？

**Comment by OkadaSatoshi** [comment]
@norotime すみませんでした。
前者です。user_idがnilになるということです。

**Comment by OkadaSatoshi** [comment]
@norotime
![2018-03-06 2](https://user-images.githubusercontent.com/29350202/37074044-fb37370e-220d-11e8-80b0-3ce527db8bbd.png)

**Comment by norotime** [comment]
@Grape-from-kai 解決できましたか！

**Comment by OkadaSatoshi** [comment]
解決できましたーありがとうございました！
